version: "3"

services:
  db:
    image: postgis/postgis:13-master
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "directus"
    restart: "always"
    volumes:
      - db_data:/var/lib/postgresql/data


  directus:
    image: directus/directus
    restart: "always"
    ports:
      - "8055:8055"
    depends_on:
      - db
    environment:
      KEY: "deft"
      SECRET: "rfzeffze"

      DB_CLIENT: "pg"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "user"
      DB_PASSWORD: "pass"
    
      ADMIN_EMAIL: test@test.com
      ADMIN_PASSWORD: test

    volumes:
      - uploads:/directus/uploads

volumes:
  db_data:
  uploads: