version: "3"

services:
  web:
    build: .
    working_dir: /app
    command: ["index.js"]
    # entrypoint: ["node"]
    # ports:
    #   - 3000:3000
    volumes:
      - ./index.js:/app/index.js
    # networks:
    #   - myapp_network
    labels:
      com.exemple.key: "value"


networks:
  # myapp_network:
  default:
    external: 
      name: "externe"
