name: CI

on: 
  push:
    branches:
      - master
    pull_request:
      branches:
        - master



jobs:
  tests:
    runs-on: ubuntu-lastest
    strategy: 
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS ${{ mastrix.node-version }} 
        uses: actions/setup-node@v3
        with:
          node-version: ${{ mastrix.node-version }} 
          cache: npm
      - run npm i
      - run npm test
      